/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppointmentCard: typeof import('./src/components/appointments/AppointmentCard.vue')['default']
    AppointmentDialog: typeof import('./src/components/appointments/AppointmentDialog.vue')['default']
    AppointmentGrid: typeof import('./src/components/appointments/AppointmentGrid.vue')['default']
    PractitionerCard: typeof import('./src/components/appointments/PractitionerCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleAppointmentGrid: typeof import('./src/components/SimpleAppointmentGrid.vue')['default']
    TestComponent: typeof import('./src/components/TestComponent.vue')['default']
  }
}
