/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppointmentCard: typeof import('./src/components/appointments/AppointmentCard.vue')['default']
    AppointmentDialog: typeof import('./src/components/appointments/AppointmentDialog.vue')['default']
    AppointmentGrid: typeof import('./src/components/appointments/AppointmentGrid.vue')['default']
    Autocomplete: typeof import('./src/components/controls/Autocomplete.vue')['default']
    FieldMap: typeof import('./src/components/controls/FieldMap.vue')['default']
    Fields: typeof import('./src/components/controls/Fields.vue')['default']
    Link: typeof import('./src/components/controls/Link.vue')['default']
    OTRosterCell: typeof import('./src/components/roster/OTRosterCell.vue')['default']
    PaymentDialog: typeof import('./src/components/appointments/PaymentDialog.vue')['default']
    PractitionerCard: typeof import('./src/components/appointments/PractitionerCard.vue')['default']
    Print: typeof import('./src/components/controls/Print.vue')['default']
    RosterCell: typeof import('./src/components/roster/RosterCell.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
