exclude: "node_modules|.git"
default_stages: [commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        files: "hms_tz.*"
        exclude: ".*json$|.*txt$|.*csv|.*md"
      - id: check-yaml
      - id: no-commit-to-branch
        args: ["--branch", "develop", "--branch", "master", "--branch", "production"]
      - id: check-merge-conflict
      - id: check-ast

  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        # Configure black to handle line length
        args: ["--line-length", "120"]
        files: "^hms_tz/.*\\.py$"
        # Make black report issues but not block the commit
        stages: [manual]

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "120"]
        files: "^hms_tz/.*\\.py$"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types_or: [javascript, vue, scss]
        files: "^hms_tz/.*\\.(js|vue|scss)$"
        args: [
          "--write",
          "--print-width=79",
          "--tab-width=2",
          "--use-tabs=false",
          "--semi=true",
          "--single-quote=false",
          "--trailing-comma=es5",
          "--bracket-spacing=true",
          "--arrow-parens=always",
          "--end-of-line=lf",
        ]
        # Ignore any files that might contain jinja / bundles
        exclude: |
          (?x)^(
              hms_tz/public/dist/.*|
              cypress/.*|
              .*node_modules.*|
              .*boilerplate.*
          )$

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.44.0
    hooks:
      - id: eslint
        types_or: [javascript]
        files: "^hms_tz/.*\\.js$"
        args: ["--quiet", "--fix"]
        additional_dependencies:
          - eslint@8.44.0
          - "@babel/eslint-parser@7.22.9"
          - "@babel/core@7.22.9"
          - "@babel/preset-env@7.22.9"
          - "@babel/plugin-proposal-class-properties@7.18.6"
        # Ignore any files that might contain jinja / bundles
        exclude: |
          (?x)^(
              hms_tz/public/dist/.*|
              cypress/.*|
              .*node_modules.*|
              .*boilerplate.*
          )$

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
        - id: flake8
          additional_dependencies: [flake8-isort, flake8-bugbear]
          files: "^hms_tz/.*\\.py$"
          args: ["--max-line-length=120", "--ignore=E203,W503"]
          # Make flake8 report issues but not block the commit
          stages: [manual]

  - repo: https://github.com/myint/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args: [
          "--in-place",
          "--remove-all-unused-imports",
          "--remove-unused-variables",
          "--ignore-init-module-imports",
        ]
        files: "^hms_tz/.*\\.py$"

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4
    hooks:
      - id: autopep8
        args: [
          "--in-place",
          "--aggressive",
          "--aggressive",
          "--max-line-length=120",
        ]
        files: "^hms_tz/.*\\.py$"
        # Make autopep8 report issues but not block the commit
        stages: [manual]

ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
